leftnav:
- identifier: 25e2e85a-56cc-88e5-ba76-ff19a4f1ccec
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 04254152-9a51-848b-e698-66afa39f1e5f
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 8d3bdf99-82fb-17ae-11d8-85e1d32b7611
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 372d9d6e-7fbf-5010-8feb-41f111353735
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
